## Data Analysis Exercise

Tasks:

1) **Create Metadata**: Write metadata files for the following datasets:

baseline_data.csv

blood_data.csv

diag_data.csv

Optional: Create metadata for all other .csv files located in the /Data directory.

2) **Translate SKS to ICD-10**: In the dict_data.csv dataset, translate the SKS codes into ICD-10 codes. Create a script that checks the SKS code and adds the corresponding ICD-10 code as a new column.

Hint: The ICD-10 codes can be found on this database site: https://icd.who.int/browse10/2019/en.

Optional: Make the same script for the diag_data.csv. 

3) **Identify Data Biases**: Identify and describe any potential biases present in the baseline_data.csv and events.csv datasets.

Optional: Identify biases in the remaining .csv files.

4) **Find Danish Registries**: Identify Danish registries that contain similar data to the 1.csv, 2.csv, and 3.csv datasets. **DEVNOTE: Maybe remove this exercise? It is maybe too much work or not really important for the course**

In [67]:
import pandas as pd

### 1) Create Metadata: Write metadata files for the following datasets:

baseline_data.csv

blood_data.csv

diag_data.csv

In [68]:
baseline_data = pd.read_csv("Data/baseline_data.csv")
blood_data = pd.read_csv("Data/blood_data.csv")
diag_data = pd.read_csv("Data/diag_data.csv")

In [69]:
baseline_data

       id     sex     d.birth  smoking
0       2  female  1941-07-14   former
1       3    male  1931-10-02   former
2       4    male  1944-11-22    never
3       5  female  1939-04-13  current
4       6    male  1962-04-18  current
..    ...     ...         ...      ...
737  1592  female  1942-04-06  current
738  1593    male  1950-02-08  current
739  1594  female  1928-12-07    never
740  1595    male  1942-08-27  current
741  1596  female  1936-04-05   former

[742 rows x 4 columns]

In [70]:
# Metadata for baseline_data 
print("="*100)
print("Metadata DataFrame for: baseline_data")
print("="*100)
baseline_metadata_df = pd.DataFrame({
    'Data Type': baseline_data.dtypes,
}).reset_index().rename(columns={'index': 'Column Name'})

baseline_descriptions = {
    "id": "Unique identifier for each patient",
    "sex": "Biological sex of the patient",
    "d.birth": "Patient's date of birth",
    "smoking": "Smoking status of the patient (current, former, never)"
}
baseline_metadata_df['Description'] = baseline_metadata_df['Column Name'].map(baseline_descriptions)
print(baseline_metadata_df.to_string())


# Metadata for dict_data
print("="*100)
print("Metadata DataFrame for: dict_data")
print("="*100)
dict_metadata_df = pd.DataFrame({
    'Data Type': dict_data.dtypes,
}).reset_index().rename(columns={'index': 'Column Name'})

# Add a description column
dict_descriptions = {
    "Unnamed: 0": "Index for the diagnosis",
    "diag": "Name of the diagnosis",
    "code": "Diagnostic code (SKS)"
}
dict_metadata_df['Description'] = dict_metadata_df['Column Name'].map(dict_descriptions)
print(dict_metadata_df.to_string())


# Metadata for events 
print("="*100)
print("Metadata DataFrame for: events")
print("="*100)
# Create a DataFrame from the metadata
events_metadata_df = pd.DataFrame({
    'Data Type': events.dtypes,
}).reset_index().rename(columns={'index': 'Column Name'})

events_descriptions = {
    "Unnamed: 0": "Index for the diagnosis",
    "id": "Unique identifier for each patient",
    "date": "Date the event occurred",
    "event": "Description of the medical event, e.g Malignancy",
    "type": "Classification of the event type (minor, major, death)"
}
events_metadata_df['Description'] = events_metadata_df['Column Name'].map(events_descriptions)

print(events_metadata_df.to_string())

====================================================================================================
Metadata DataFrame for: baseline_data
====================================================================================================
  Column Name Data Type                                             Description
0          id     int64                      Unique identifier for each patient
1         sex    object                           Biological sex of the patient
2     d.birth    object                                 Patient's date of birth
3     smoking    object  Smoking status of the patient (current, former, never)
====================================================================================================
Metadata DataFrame for: dict_data
====================================================================================================
  Column Name Data Type              Description
0  Unnamed: 0     int64  Index for the diagnosis
1        diag    object    Name of the diagnosis
2        code    object    Diagnostic code (SKS)
====================================================================================================
Metadata DataFrame for: events
====================================================================================================
  Column Name Data Type                                             Description
0  Unnamed: 0     int64                                 Index for the diagnosis
1          id     int64                      Unique identifier for each patient
2        date    object                                 Date the event occurred
3       event    object        Description of the medical event, e.g Malignancy
4        type    object  Classification of the event type (minor, major, death)

2) Translate SKS to ICD-10: In the dict_data.csv dataset, translate the SKS codes into ICD-10 codes. Create a script that checks the SKS code and adds the corresponding ICD-10 code as a new column.
Hint: The ICD-10 codes can be found on this database site: https://icd.who.int/browse10/2019/en.

In [83]:
dict_data

   Unnamed: 0            diag    code
0           1        diabetes    DE10
1           2    hypertension  BZFC8A
2           3  hyperlipidemia   DE782

In [89]:
icd_codes = []

for code_value in dict_data['code']:
    if code_value == "DE10":
        icd_codes.append('E10')
    elif code_value == "BZFC8A":
        icd_codes.append('E78.5')
    elif code_value == "DE782":
        icd_codes.append('I10')
    else:
            break

dict_data['ICD-10_code'] = icd_codes

dict_data

   Unnamed: 0            diag    code ICD-10_code
0           1        diabetes    DE10         E10
1           2    hypertension  BZFC8A       E78.5
2           3  hyperlipidemia   DE782         I10

3) **Identify Data Biases**: Identify and describe any potential biases present in the baseline_data.csv and events.csv datasets.

In [96]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  709 non-null    int64
 1   id          709 non-null    int64
 2   date        709 non-null    object
 3   event       709 non-null    object
 4   type        709 non-null    object
dtypes: int64(2), object(3)
memory usage: 27.8+ KB

In [92]:
baseline_data

       id     sex     d.birth  smoking
0       2  female  1941-07-14   former
1       3    male  1931-10-02   former
2       4    male  1944-11-22    never
3       5  female  1939-04-13  current
4       6    male  1962-04-18  current
..    ...     ...         ...      ...
737  1592  female  1942-04-06  current
738  1593    male  1950-02-08  current
739  1594  female  1928-12-07    never
740  1595    male  1942-08-27  current
741  1596  female  1936-04-05   former

[742 rows x 4 columns]

In [73]:
baseline_data = pd.read_csv("Data/baseline_data.csv")
blood_data = pd.read_csv("Data/blood_data.csv")
diag_data = pd.read_csv("Data/diag_data.csv")
dict_data = pd.read_csv("Data/dict_data.csv")
events = pd.read_csv("Data/events.csv")
quest_data = pd.read_csv("Data/quest_data.csv")
snomed_data = pd.read_csv("Data/snomed_data.csv")
treat_data = pd.read_csv("Data/treat_data.csv")
visit_date = pd.read_csv("Data/visit_date.csv")

In [74]:
baseline_data = pd.read_csv("Data/baseline_data.csv")
blood_data = pd.read_csv("Data/blood_data.csv")
diag_data = pd.read_csv("Data/diag_data.csv")

In [75]:
baseline_data

       id     sex     d.birth  smoking
0       2  female  1941-07-14   former
1       3    male  1931-10-02   former
2       4    male  1944-11-22    never
3       5  female  1939-04-13  current
4       6    male  1962-04-18  current
..    ...     ...         ...      ...
737  1592  female  1942-04-06  current
738  1593    male  1950-02-08  current
739  1594  female  1928-12-07    never
740  1595    male  1942-08-27  current
741  1596  female  1936-04-05   former

[742 rows x 4 columns]

In [76]:
dict_data

   Unnamed: 0            diag    code
0           1        diabetes    DE10
1           2    hypertension  BZFC8A
2           3  hyperlipidemia   DE782

In [77]:
events

     Unnamed: 0    id        date              event   type
0             1     2  2010-05-07         malignancy  other
1             2     2  2011-11-07        other death  death
2             3     5  2008-03-31  revascularization  minor
3             4     6  2006-07-18  revascularization  minor
4             5     6  2006-09-19  revascularization  minor
..          ...   ...         ...                ...    ...
704         705  1568  2008-09-27             stroke  major
705         706  1568  2008-11-14  revascularization  minor
706         707  1592  2007-01-22  revascularization  minor
707         708  1592  2007-01-23  revascularization  minor
708         709  1596  2006-02-28        other death  death

[709 rows x 5 columns]

In [78]:
quest_data

      Unnamed: 0    id      date.x  anxiety  sleep  alcohol  fruit  vegetable
0              1     2  2005-04-03        3      3        1    3.0          3
1              2     2  2006-09-16        4      3        1    3.0          3
2              3     2  2007-08-07        3      1        1    4.0          3
3              4     2  2008-12-11        2      2        1    4.0          4
4              5     2  2009-12-20        2      4        1    4.0          3
...          ...   ...         ...      ...    ...      ...    ...        ...
3892        3893  1592  2007-05-23        2      2        1    NaN          3
3893        3894  1593  2005-11-08        2      1        3    4.0          4
3894        3895  1594  2005-08-14        2      3        1    4.0          4
3895        3896  1595  2005-08-18        2      3        2    2.0          4
3896        3897  1596  2005-10-13        3      4        1    4.0          4

[3897 rows x 8 columns]

In [79]:
snomed_data

,source,label,URL,code,text
0,diag_data,DE10,http://purl.bioontology.org/ontology/SNOMEDCT/...,73211009,Diabetes mellitus
1,diag_data,BZFC8A,http://purl.bioontology.org/ontology/SNOMEDCT/...,38341003,Hypertensive disorder
2,diag_data,DE782,http://purl.bioontology.org/ontology/SNOMEDCT/...,55822004,Hyperlipidemia

In [80]:
treat_data

,Unnamed: 0,record_id,treat_start_date,aspirin,clopridrogel,anticlot,ezetimibe,statins,ace
0,7,2,2005-06-10,1.0,0,0,0,1,NaN
1,8,2,2006-09-12,NaN,0,0,0,1,1.0
2,9,2,2007-10-15,1.0,0,0,0,1,1.0
3,10,2,2008-09-22,1.0,0,0,0,1,NaN
4,11,2,2009-09-21,1.0,0,0,0,1,NaN
...,...,...,...,...,...,...,...,...,...
3897,8169,1592,2007-06-09,NaN,0,0,0,1,NaN
3898,8170,1593,2005-11-07,NaN,0,0,0,1,1.0
3899,8171,1594,2005-10-03,1.0,0,0,0,1,NaN
3900,8172,1595,2005-06-02,1.0,0,0,0,1,1.0
3901,8173,1596,2005-12-20,NaN,0,0,0,1,NaN

In [81]:
visit_date

      Unnamed: 0    id  visit_date
0              7     2  2005-06-10
1              8     2  2006-09-12
2              9     2  2007-10-15
3             10     2  2008-09-22
4             11     2  2009-09-21
...          ...   ...         ...
3897        8169  1592  2007-06-09
3898        8170  1593  2005-11-07
3899        8171  1594  2005-10-03
3900        8172  1595  2005-06-02
3901        8173  1596  2005-12-20

[3902 rows x 3 columns]