## Data Sources and Data Acquisition Exercise

Tasks:

1) **Create Metadata**: Write metadata files for the following datasets:

baseline_data.csv

blood_data.csv

diag_data.csv

Optional: Create metadata for all other .csv files located in the /Data directory.

2) **Translate SKS to ICD-10**: In the dict_data.csv dataset, translate the SKS codes into ICD-10 codes. Create a script that checks the SKS code and adds the corresponding ICD-10 code as a new column.

Hint: The ICD-10 codes can be found on this database site: https://icd.who.int/browse10/2019/en.

Optional: Make the same script for the diag_data.csv. 


3) **Find Danish Registries**: Identify Danish registries that contain similar data to the baseline_data.csv, blood_data.csv, and diag_data.csv datasets.

## 1) Create Metadata: Write metadata files for the following datasets:

baseline_data.csv

blood_data.csv

diag_data.csv

In [3]:
import pandas as pd

baseline_data = pd.read_csv("data/baseline_data.csv")
blood_data = pd.read_csv("data/blood_data.csv")
diag_data = pd.read_csv("data/diag_data.csv")
dict_data = pd.read_csv("data/dict_data.csv")
events = pd.read_csv("data/events.csv")

In [4]:
baseline_data

       id     sex     d.birth  smoking
0       2  female  1941-07-14   former
1       3    male  1931-10-02   former
2       4    male  1944-11-22    never
3       5  female  1939-04-13  current
4       6    male  1962-04-18  current
..    ...     ...         ...      ...
737  1592  female  1942-04-06  current
738  1593    male  1950-02-08  current
739  1594  female  1928-12-07    never
740  1595    male  1942-08-27  current
741  1596  female  1936-04-05   former

[742 rows x 4 columns]

In [8]:
print("-"*100)
print("Metadata DataFrame for: baseline_data")
print("-"*100)
baseline_metadata_df = pd.DataFrame({
    'Data Type': baseline_data.dtypes,
}).reset_index().rename(columns={'index': 'Column Name'})

baseline_descriptions = {
    "id": "Unique identifier for each patient",
    "sex": "Biological sex of the patient",
    "d.birth": "Patient's date of birth",
    "smoking": "Smoking status of the patient (current, former, never)"
}
baseline_metadata_df['Description'] = baseline_metadata_df['Column Name'].map(baseline_descriptions)
print(baseline_metadata_df.to_string())


# Metadata for dict_data
print("-"*100)
print("Metadata DataFrame for: dict_data")
print("-"*100)
dict_metadata_df = pd.DataFrame({
    'Data Type': dict_data.dtypes,
}).reset_index().rename(columns={'index': 'Column Name'})

# Description column
dict_descriptions = {
    "Unnamed: 0": "Index for the diagnosis",
    "diag": "Name of the diagnosis",
    "code": "Diagnostic code (SKS)"
}
dict_metadata_df['Description'] = dict_metadata_df['Column Name'].map(dict_descriptions)
print(dict_metadata_df.to_string())


# Metadata for events 
print("-"*100)
print("Metadata DataFrame for: events")
print("-"*100)
# Create a DataFrame from the metadata
events_metadata_df = pd.DataFrame({
    'Data Type': events.dtypes,
}).reset_index().rename(columns={'index': 'Column Name'})

events_descriptions = {
    "Unnamed: 0": "Index for the diagnosis",
    "id": "Unique identifier for each patient",
    "date": "Date the event occurred",
    "event": "Description of the medical event, e.g Malignancy",
    "type": "Classification of the event type (minor, major, death)"
}
events_metadata_df['Description'] = events_metadata_df['Column Name'].map(events_descriptions)

print(events_metadata_df.to_string())

----------------------------------------------------------------------------------------------------
Metadata DataFrame for: baseline_data
----------------------------------------------------------------------------------------------------
  Column Name Data Type                                             Description
0          id     int64                      Unique identifier for each patient
1         sex    object                           Biological sex of the patient
2     d.birth    object                                 Patient's date of birth
3     smoking    object  Smoking status of the patient (current, former, never)
----------------------------------------------------------------------------------------------------
Metadata DataFrame for: dict_data
----------------------------------------------------------------------------------------------------
   Column Name Data Type              Description
0   Unnamed: 0     int64  Index for the diagnosis
1         diag    object    Name of the diagnosis
2         code    object    Diagnostic code (SKS)
3  ICD-10_code    object                      NaN
----------------------------------------------------------------------------------------------------
Metadata DataFrame for: events
----------------------------------------------------------------------------------------------------
  Column Name Data Type                                             Description
0  Unnamed: 0     int64                                 Index for the diagnosis
1          id     int64                      Unique identifier for each patient
2        date    object                                 Date the event occurred
3       event    object        Description of the medical event, e.g Malignancy
4        type    object  Classification of the event type (minor, major, death)

## 2) Translate SKS to ICD-10: In the dict_data.csv dataset, translate the SKS codes into ICD-10 codes. Create a script that checks the SKS code and adds the corresponding ICD-10 code as a new column.
Hint: The ICD-10 codes can be found on this database site: https://icd.who.int/browse10/2019/en.

In [6]:
dict_data

   Unnamed: 0            diag    code
0           1        diabetes    DE10
1           2    hypertension  BZFC8A
2           3  hyperlipidemia   DE782

In [7]:
icd_codes = []

for code_value in dict_data['code']:
    if code_value == "DE10":
        icd_codes.append('E10')
    elif code_value == "BZFC8A":
        icd_codes.append('E78.5')
    elif code_value == "DE782":
        icd_codes.append('I10')
    else:
            break

dict_data['ICD-10_code'] = icd_codes

dict_data

   Unnamed: 0            diag    code ICD-10_code
0           1        diabetes    DE10         E10
1           2    hypertension  BZFC8A       E78.5
2           3  hyperlipidemia   DE782         I10

## 3) **Find Danish Registries**: Identify Danish registries that contain similar data to the baseline_data.csv, blood_data.csv, and diag_data.csv datasets.

In [9]:
baseline_data

       id     sex     d.birth  smoking
0       2  female  1941-07-14   former
1       3    male  1931-10-02   former
2       4    male  1944-11-22    never
3       5  female  1939-04-13  current
4       6    male  1962-04-18  current
..    ...     ...         ...      ...
737  1592  female  1942-04-06  current
738  1593    male  1950-02-08  current
739  1594  female  1928-12-07    never
740  1595    male  1942-08-27  current
741  1596  female  1936-04-05   former

[742 rows x 4 columns]

In [14]:
dict_data

   Unnamed: 0            diag    code ICD-10_code
0           1        diabetes    DE10         E10
1           2    hypertension  BZFC8A       E78.5
2           3  hyperlipidemia   DE782         I10

In [15]:
events

     Unnamed: 0    id        date              event   type
0             1     2  2010-05-07         malignancy  other
1             2     2  2011-11-07        other death  death
2             3     5  2008-03-31  revascularization  minor
3             4     6  2006-07-18  revascularization  minor
4             5     6  2006-09-19  revascularization  minor
..          ...   ...         ...                ...    ...
704         705  1568  2008-09-27             stroke  major
705         706  1568  2008-11-14  revascularization  minor
706         707  1592  2007-01-22  revascularization  minor
707         708  1592  2007-01-23  revascularization  minor
708         709  1596  2006-02-28        other death  death

[709 rows x 5 columns]